In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spotify_millsongdata.csv")

In [3]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [4]:
df.shape

(57650, 4)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57650 entries, 0 to 57649
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   artist  57650 non-null  str
 1   song    57650 non-null  str
 2   link    57650 non-null  str
 3   text    57650 non-null  str
dtypes: str(4)
memory usage: 72.7 MB

In [6]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [7]:
df["artist"].nunique()

643

In [9]:
df["artist"].value_counts().head(10)

artist
Donna Summer        191
Gordon Lightfoot    189
Bob Dylan           188
George Strait       188
Alabama             187
Cher                187
Loretta Lynn        187
Reba Mcentire       187
Chaka Khan          186
Dean Martin         186
Name: count, dtype: int64

In [10]:
df.describe(include="all")

,artist,song,link,text
count,57650,57650,57650,57650
unique,643,44824,57650,57494
top,Donna Summer,Have Yourself A Merry Little Christmas,/a/abba/ahes+my+kind+of+girl_20598417.html,Chestnuts roasting on an open fire \r\nJack F...
freq,191,35,1,6

In [12]:
df["word_count"] = df["text"].apply(lambda x: len(str(x).split()))

In [13]:
df[["song", "artist", "word_count"]].head()

                    song artist  word_count
0  Ahe's My Kind Of Girl   ABBA         153
1       Andante, Andante   ABBA         260
2         As Good As New   ABBA         312
3                   Bang   ABBA         200
4       Bang-A-Boomerang   ABBA         198