In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spotify_millsongdata.csv")

In [3]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [4]:
df["text"].iloc[0]

"Look at her face, it's a wonderful face  \r\nAnd it means something special to me  \r\nLook at the way that she smiles when she sees me  \r\nHow lucky can one fellow be?  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?  \r\n  \r\nAnd when we go for a walk in the park  \r\nAnd she holds me and squeezes my hand  \r\nWe'll go on walking for hours and talking  \r\nAbout all the things that we plan  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?\r\n\r\n"

In [5]:
df["cleaned_text"] = df["text"]

In [6]:
df["cleaned_text"] = df["cleaned_text"].str.lower()

In [7]:
df["cleaned_text"] = df["cleaned_text"].str.replace(r"\r\n", " ", regex=True)

In [8]:
df["cleaned_text"] = df["cleaned_text"].str.replace(r"\s+", " ", regex=True).str.strip()

In [9]:
df[["text", "cleaned_text"]].head(1)

,text,cleaned_text
0,"Look at her face, it's a wonderful face \r\nA...","look at her face, it's a wonderful face and it..."

In [10]:
print(df["cleaned_text"].iloc[0])

look at her face, it's a wonderful face and it means something special to me look at the way that she smiles when she sees me how lucky can one fellow be? she's just my kind of girl, she makes me feel fine who could ever believe that she could be mine? she's just my kind of girl, without her i'm blue and if she ever leaves me what could i do, what could i do? and when we go for a walk in the park and she holds me and squeezes my hand we'll go on walking for hours and talking about all the things that we plan she's just my kind of girl, she makes me feel fine who could ever believe that she could be mine? she's just my kind of girl, without her i'm blue and if she ever leaves me what could i do, what could i do?